<a href="https://colab.research.google.com/github/Toxxi-frank/Deeplearning/blob/main/Bai_tap_sinh_tu.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!wget --no-check-certificate \
    https://storage.googleapis.com/protonx-cloud-storage/data.txt


--2021-06-22 14:56:50--  https://storage.googleapis.com/protonx-cloud-storage/data.txt
Resolving storage.googleapis.com (storage.googleapis.com)... 64.233.188.128, 64.233.189.128, 108.177.97.128, ...
Connecting to storage.googleapis.com (storage.googleapis.com)|64.233.188.128|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 93578 (91K) [text/plain]
Saving to: ‘data.txt’

data.txt            100%[===================>]  91.38K  --.-KB/s    in 0.001s  

2021-06-22 14:56:51 (82.6 MB/s) - ‘data.txt’ saved [93578/93578]



In [ ]:
# download dataset

In [ ]:
data = open('data.txt').read()

In [ ]:
data

"FROM fairest creatures we desire increase,\nThat thereby beauty's rose might never die,\nBut as the riper should by time decease,\nHis tender heir might bear his memory:\nBut thou, contracted to thine own bright eyes,\nFeed'st thy light'st flame with self-substantial fuel,\nMaking a famine where abundance lies,\nThyself thy foe, to thy sweet self too cruel.\nThou that art now the world's fresh ornament\nAnd only herald to the gaudy spring,\nWithin thine own bud buriest thy content\nAnd, tender churl, makest waste in niggarding.\nPity the world, or else this glutton be,\nTo eat the world's due, by the grave and thee.\nWhen forty winters shall beseige thy brow,\nAnd dig deep trenches in thy beauty's field,\nThy youth's proud livery, so gazed on now,\nWill be a tatter'd weed, of small worth held:\nThen being ask'd where all thy beauty lies,\nWhere all the treasure of thy lusty days,\nTo say, within thine own deep-sunken eyes,\nWere an all-eating shame and thriftless praise.\nHow much mor

In [ ]:
corpus = data.lower().split("\n")
# tách ra thành từng câu và chuyển thành chữ thường (ko viết hoa)

In [ ]:
corpus

['from fairest creatures we desire increase,',
 "that thereby beauty's rose might never die,",
 'but as the riper should by time decease,',
 'his tender heir might bear his memory:',
 'but thou, contracted to thine own bright eyes,',
 "feed'st thy light'st flame with self-substantial fuel,",
 'making a famine where abundance lies,',
 'thyself thy foe, to thy sweet self too cruel.',
 "thou that art now the world's fresh ornament",
 'and only herald to the gaudy spring,',
 'within thine own bud buriest thy content',
 'and, tender churl, makest waste in niggarding.',
 'pity the world, or else this glutton be,',
 "to eat the world's due, by the grave and thee.",
 'when forty winters shall beseige thy brow,',
 "and dig deep trenches in thy beauty's field,",
 "thy youth's proud livery, so gazed on now,",
 "will be a tatter'd weed, of small worth held:",
 "then being ask'd where all thy beauty lies,",
 'where all the treasure of thy lusty days,',
 'to say, within thine own deep-sunken eyes,',

In [ ]:
from tensorflow.keras.preprocessing.text import Tokenizer

In [ ]:
tokenizer = Tokenizer()
tokenizer.fit_on_texts(corpus)
total_words = len(tokenizer.word_index) + 1

input_sequences = []
for line in corpus:
  token_list = tokenizer.texts_to_sequences([line])[0]
  for i in range(1, len(token_list)):
    n_gram_sequence = token_list[:i+1]
    print(n_gram_sequence)
    input_sequences.append(n_gram_sequence) 

Streaming output truncated to the last 5000 lines.
[153, 5, 174]
[153, 5, 174, 3]
[153, 5, 174, 3, 856]
[153, 5, 174, 3, 856, 857]
[66, 209]
[66, 209, 2595]
[66, 209, 2595, 287]
[66, 209, 2595, 287, 150]
[66, 209, 2595, 287, 150, 2596]
[858, 206]
[858, 206, 1]
[858, 206, 1, 1299]
[858, 206, 1, 1299, 13]
[858, 206, 1, 1299, 13, 23]
[858, 206, 1, 1299, 13, 23, 5]
[858, 206, 1, 1299, 13, 23, 5, 400]
[858, 206]
[858, 206, 1]
[858, 206, 1, 1299]
[858, 206, 1, 1299, 2597]
[858, 206, 1, 1299, 2597, 3]
[858, 206, 1, 1299, 2597, 3, 160]
[858, 206, 1, 1299, 2597, 3, 160, 249]
[1, 7]
[1, 7, 29]
[1, 7, 29, 205]
[1, 7, 29, 205, 13]
[1, 7, 29, 205, 13, 5]
[1, 7, 29, 205, 13, 5, 488]
[1, 7, 29, 205, 13, 5, 488, 411]
[348, 2598]
[348, 2598, 7]
[348, 2598, 7, 66]
[348, 2598, 7, 66, 26]
[348, 2598, 7, 66, 26, 1298]
[348, 2598, 7, 66, 26, 1298, 471]
[348, 2598, 7, 66, 26, 1298, 471, 1258]
[858, 206]
[858, 206, 1]
[858, 206, 1, 75]
[858, 206, 1, 75, 147]
[858, 206, 1, 75, 147, 39]
[858, 206, 1, 75, 147, 3

In [ ]:
from tensorflow.keras.preprocessing.sequence import pad_sequences
import numpy as np
import tensorflow.keras.utils as ku

In [ ]:
#pad_sequences
max_sequence_len = max([len(x) for x in input_sequences])
input_sequences = np.array(pad_sequences(input_sequences, maxlen = max_sequence_len, padding='pre'))

#create prediction and labels
predictors, label = input_sequences[:,:-1], input_sequences[:,-1]
label = ku.to_categorical(label, num_classes = total_words)

In [ ]:
predictors

array([[   0,    0,    0, ...,    0,    0,   34],
       [   0,    0,    0, ...,    0,   34,  417],
       [   0,    0,    0, ...,   34,  417,  877],
       ...,
       [   0,    0,    0, ..., 3209,  493,  493],
       [   0,    0,    0, ...,  493,  493, 3210],
       [   0,    0,    0, ...,  493, 3210,   15]], dtype=int32)

In [ ]:
print(label)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [ ]:
from tensorflow.keras.layers import Dense, Embedding, Bidirectional, Dropout, LSTM
from tensorflow.keras.models import Sequential
from tensorflow.keras import regularizers

In [ ]:
model = Sequential()
model.add(Embedding(total_words, 100, input_length = max_sequence_len -1))
model.add(Bidirectional(LSTM(150, return_sequences = True)))
model.add(Dropout(0.2))
model.add(LSTM(100))
model.add(Dense(total_words/2, activation = 'relu', kernel_regularizer = regularizers.l2(0.01)))
model.add(Dense(total_words, activation = 'softmax'))


In [ ]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 10, 100)           321100    
_________________________________________________________________
bidirectional (Bidirectional (None, 10, 300)           301200    
_________________________________________________________________
dropout (Dropout)            (None, 10, 300)           0         
_________________________________________________________________
lstm_1 (LSTM)                (None, 100)               160400    
_________________________________________________________________
dense (Dense)                (None, 1605)              162105    
_________________________________________________________________
dense_1 (Dense)              (None, 3211)              5156866   
Total params: 6,101,671
Trainable params: 6,101,671
Non-trainable params: 0
______________________________________________

In [ ]:
model.compile(optimizer= 'adam', loss = "categorical_crossentropy", metrics = ['acc'])


In [ ]:
history = model.fit(predictors, label, epochs = 100, verbose=1)

Epoch 1/100
484/484 [==============================] - 23s 28ms/step - loss: 6.9083 - acc: 0.0201
Epoch 2/100
484/484 [==============================] - 13s 28ms/step - loss: 6.4993 - acc: 0.0206
Epoch 3/100
484/484 [==============================] - 13s 27ms/step - loss: 6.3887 - acc: 0.0257
Epoch 4/100
484/484 [==============================] - 13s 27ms/step - loss: 6.2673 - acc: 0.0303
Epoch 5/100
484/484 [==============================] - 13s 27ms/step - loss: 6.1815 - acc: 0.0369
Epoch 6/100
484/484 [==============================] - 13s 27ms/step - loss: 6.1024 - acc: 0.0390
Epoch 7/100
484/484 [==============================] - 13s 27ms/step - loss: 6.0226 - acc: 0.0411
Epoch 8/100
484/484 [==============================] - 13s 27ms/step - loss: 5.9402 - acc: 0.0446
Epoch 9/100
484/484 [==============================] - 13s 27ms/step - loss: 5.8466 - acc: 0.0497
Epoch 10/100
484/484 [==============================] - 13s 27ms/step - loss: 5.7465 - acc: 0.0553
Epoch 11/100
484/48

In [ ]:
test_seq = 'despite of wrinkles'

next_words = 10
for _ in range(next_words):
  token_list = tokenizer.texts_to_sequences([test_seq])[0]
  token_list = pad_sequences([token_list], maxlen = max_sequence_len - 1, padding='pre')
  predicted = np.argmax(model.predict(token_list))
  output_words = ''

  for word, index in tokenizer.word_index.items():
    if index==predicted:
      output_words = word
      break
  test_seq += " " + output_words
print(test_seq)

despite of wrinkles this thy golden time is in thee aside much grow


In [ ]:
test_seq

'despite of wrinkles this thy golden time is in thee aside much grow'